[build]
  base = ""
  command = "npm --prefix ui install && npm --prefix ui run build"
  publish = "ui/dist"
  functions = "api"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

